# Generated by Django 5.0.5 on 2024-05-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.ImageField(null=True, upload_to='ids'),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfie',
            field=models.ImageField(null=True, upload_to='selfie'),
        ),
    ]
