# Generated by Django 3.2.20 on 2024-07-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(max_length=1000),
        ),
    ]
