# Generated by Django 3.2.20 on 2024-07-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_user_signup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.BooleanField(default=False),
        ),
    ]
