# Generated by Django 3.2.20 on 2024-08-17 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0010_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateField(auto_created=django.utils.timezone.now, auto_now_add=True),
        ),
    ]
