# Generated by Django 3.2.20 on 2024-08-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='ids'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(blank=True, default='No number', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfie'),
        ),
    ]
