# Generated by Django 3.2.20 on 2024-08-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_auto_20240817_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
