# Generated by Django 3.2.20 on 2024-05-24 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryChoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=100)),
                ('job_slug', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_thumbnail', models.ImageField(upload_to='JobThumb')),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('job_category', models.ManyToManyField(to='Jobs.JobCategoryChoice')),
                ('job_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
