# Generated by Django 5.1 on 2024-09-04 12:00

import Jobs.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='job_deadline',
            field=models.DateField(default=Jobs.models.Job.default_deadline),
        ),
        migrations.AddField(
            model_name='job',
            name='job_open',
            field=models.BooleanField(default=True),
        ),
    ]
