# Generated by Django 5.1 on 2024-09-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_job_created_at_job_job_deadline_job_job_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='currency',
            field=models.CharField(choices=[('Rwf', 'Rwf'), ('USD', 'USD')], default='Rwf', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='job_max_salary',
            field=models.IntegerField(default=50000),
        ),
        migrations.AddField(
            model_name='job',
            name='job_min_salary',
            field=models.IntegerField(default=10000),
        ),
    ]
