# Generated by Django 5.1 on 2024-09-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_job_currency_job_job_max_salary_job_job_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
