# Generated by Django 5.1 on 2024-09-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
