# Generated by Django 3.2.20 on 2024-05-24 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('thumbbail', models.ImageField(upload_to='News')),
            ],
        ),
    ]
