# Generated by Django 3.2.20 on 2024-06-16 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='thumbbail',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
