# Generated by Django 3.2.20 on 2024-05-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='place',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Vip', 'Vip')], default='Normal', max_length=255),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to='Account.user'),
        ),
    ]
