# Generated by Django 3.2.20 on 2024-05-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productmodel_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopmodel',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shopmodel',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
