# Generated by Django 3.2.20 on 2024-07-08 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20240525_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurAds',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='OurAds/')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Our Ads',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='shopmodel',
            options={'verbose_name_plural': 'Shops'},
        ),
    ]
