# Generated by Django 3.2.20 on 2024-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20240708_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
