# Generated by Django 3.2.20 on 2024-07-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_shopmodel_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='currency',
            field=models.CharField(choices=[('Rwf', 'Rwf'), ('USD', 'USD')], default='Rwf', max_length=100),
        ),
    ]
