# Generated by Django 3.2.20 on 2024-08-06 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_categoryfeatures_productfeatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Features of Product'},
        ),
        migrations.AddField(
            model_name='productmodel',
            name='features',
            field=models.ManyToManyField(related_name='product_features', to='Product.CategoryFeatures'),
        ),
        migrations.AlterField(
            model_name='categoryfeatures',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_features', to='Product.category'),
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
    ]
