# Generated by Django 3.2.20 on 2024-08-06 12:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_auto_20240806_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_options', to='Product.categoryfeatures')),
            ],
        ),
    ]
