# Generated by Django 3.2.20 on 2024-08-06 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_featureoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='features',
        ),
        migrations.CreateModel(
            name='ProductFeatureOptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.categoryfeatures')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.featureoptions')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feature_options', to='Product.productmodel')),
            ],
        ),
    ]
