# Generated by Django 3.2.20 on 2024-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_auto_20240812_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
