# Generated by Django 3.2.20 on 2024-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_auto_20240813_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_colours', to='Product.Colors'),
        ),
    ]
