# Generated by Django 5.1 on 2024-09-04 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_comment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
