# Generated by Django 3.2.20 on 2024-06-17 11:57

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_room_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(resource_type='video'), upload_to='Chat/Video'),
        ),
    ]
