# Generated by Django 3.2.20 on 2024-06-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_message_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='last_message',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
