# Generated by Django 3.2.20 on 2024-07-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0004_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='action',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer', 'Transfer'), ('pay', 'pay')], default='pay', max_length=255),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
