# Generated by Django 3.2.20 on 2024-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0005_auto_20240725_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='action',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdraw', 'Withdraw'), ('Transfer', 'Transfer'), ('pay', 'pay')], default='pay', max_length=255),
        ),
    ]
