# Generated by Django 3.2.20 on 2024-07-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0006_alter_payments_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='payment_ref',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
