# Generated by Django 3.2.20 on 2024-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet', '0007_wallethistory_payment_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='amount',
            field=models.IntegerField(default=10000),
        ),
    ]
